### ISSUE TITLE
Q: What is the license on this code?

### ISSUE THREAD

**Issue by JCash** [SebLague/Text-Rendering#1]
Hi Sebastian!
Thanks for the YT presentation.
While I'm looking to reimplement a similar system using C, I have the question about license, as I think the final shader may look quite similar.

I think it'd be good to add some license text/file to this repository, if you wouldn't mind.

Thanks again!
/Mathias

**Comment by SebLague** [comment]
I've added the MIT license. Let me know if you come up with any improvements for your implementation that you're willing to share :)

**Comment by JCash** [comment]
Thanks!
Fur sure, I'd be happy to share any results!

**Comment by kitremy4510** [comment]
how to actually get the renderer?
